name: Build and Test

on:
  push:
    branches:
      - develop
      - release/*
      - main
  pull_request:
    branches: 
      - develop
      - release/*
      - main
  
env:
  WORKSPACE: ${{ 'ItsME.xcworkspace' }}
  SCHEME: ${{ 'ItsME' }}
    
jobs:  
  build_and_test:
    name: Build and Test main scheme using iPhone simulator
    runs-on: macos-12
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check cache
        uses: actions/cache@v3
        id: cocoapods-cache
        with:
          path: ./Pods
          key: ${{ runner.os }}-cocoapods-v1-${{ hashFiles('./Podfile.lock') }}
      - name: Pod install when miss the cache
        if: steps.cocoapods-cache.outputs.cache-hit != 'true'
        run: pod install --repo-update --clean-install
      - name: Build for testing
        run: xcodebuild build-for-testing -workspace $WORKSPACE -scheme $SCHEME -destination 'platform=iOS Simulator,name=iPhone 14 Pro Max'
      - name: Test without building
        run: xcodebuild test-without-building -workspace $WORKSPACE -scheme $SCHEME -destination 'platform=iOS Simulator,name=iPhone 14 Pro Max'
  
